-03- B.mahmut
full-stack-course-year-2/homeworks pull request #56
Opened 2022-03-11 20:22 UTC by B-Mahmut

2022-03-12 20:34 UTC, merdonet commented on javascript_odev/hafta#2/aap.js
> +function araba(tercih) {
?? bu kisim baska bir yerden kaldi herhalde.??

2022-03-12 20:34 UTC, merdonet commented on javascript_odev/hafta#2/aap.js
> +var sonuc3 = carpma(25, 12);
hata kontrol yok!!

2022-03-13 05:59 UTC, arcevit requested changes

2022-03-13 05:59 UTC, arcevit commented on javascript_odev/hafta#2/aap.js
> +
`var` kullanma yerine `const` veya `let` kullanmani tavsiye ederim,
asagida yazdigin fonksiyonlari sayfanin ustte yazip, asagida cagirman daha guzel olur

2022-03-13 05:59 UTC, arcevit commented on javascript_odev/hafta#2/aap.js
> +
burdaya yazdigin fonksiyonlari cagirarak console.log yapman gerekiyor
normal matematiksel ifadeleri console.log icinde yazmana gerek yok

2022-03-13 05:59 UTC, arcevit commented on javascript_odev/hafta#2/aap.js
> +console.log(sonuc3);
👍

2022-03-13 05:59 UTC, arcevit commented on javascript_odev/hafta#2/aap.js
> +
fonksiyonlarinda logic olarak hata var, sifir ile sayilar carpilabilinir, negatif sayilar da bolunebilinir,
bunlari hata olarak yazmaman gerekiyor,
Hata olarak sunlari dusun
Ornegin
bir `string`, `object` veya `boolean` ile bir sayi 4 ISLEM yapilamaz bu durumlari dusunebilirsin

2022-03-20 06:05 UTC, arcevit approved these changes

2022-03-20 10:30 UTC, merged