2.branch js
full-stack-course-year-2/homeworks pull request #76
Opened 2022-03-23 22:16 UTC by Ramists

2022-03-26 19:46 UTC, skulleci reviewed
fazladan bir app.js dosyası mevcut , dersten sonra ödevleri tamamlayıp tekrar pull-request gönderebilirsiniz

2022-03-26 19:46 UTC, skulleci commented on javascript_odev/hafta4/17-Ramis/odev1.js
> +//***REDUCE***
ödevde eksikler var, tamamlayalım lütfen

2022-03-27 16:28 UTC, merdonet requested changes
kalsör dizinlerinize dikkat edin

2022-03-27 16:29 UTC, merdonet requested changes

2022-03-27 16:29 UTC, merdonet commented on javascript_odev/hafta4/odevler/odev2.js
>  // 4) Küçükten büyüğe doğru sıralanmış dizideki kişilerin bir listesini alın.
bu dosyada degisiklik yapmamaniz gerekiyor. klasör düzenlerine dikkat edin.

2022-03-27 16:36 UTC, Ramists commented on javascript_odev/hafta4/odevler/odev2.js
>  // 4) Küçükten büyüğe doğru sıralanmış dizideki kişilerin bir listesini alın.
anladım ana klasör üzerinden çözüm yapmışım o kısımda.

2022-03-27 22:07 UTC, closed without merging