02-Ahmet-5-hafta
full-stack-course-year-2/homeworks pull request #96
Opened 2022-03-29 14:19 UTC by adolsoft

2022-04-01 14:28 UTC, merdonet requested changes

2022-04-01 14:28 UTC, merdonet commented on javascript_odev/hafta#5/02-Ahmet/exp4.js
> +//console.log(users);
yorum satiri kalmis :)

2022-04-01 14:28 UTC, merdonet commented on javascript_odev/hafta#5/02-Ahmet/exp4.js
> +//addCommentUser
yorum

2022-04-01 14:28 UTC, merdonet commented on javascript_odev/hafta#5/02-Ahmet/exp5.js
> +);
}); 

prettier gibi extentionlari kullanabilirsin.

2022-04-03 11:59 UTC, adolsoft reviewed
Yotum satırı silindi diger düzenlemeler yapıldı

2022-04-03 12:00 UTC, merged